// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Data;

namespace WebApp.Migrations
{
    [DbContext(typeof(ElevatorDbContext))]
    partial class ElevatorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("WebApp.Models.Elevator", b =>
                {
                    b.Property<int>("ElevatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentFloor")
                        .HasColumnType("INTEGER");

                    b.HasKey("ElevatorId");

                    b.ToTable("Elevators");

                    b.HasData(
                        new
                        {
                            ElevatorId = 1,
                            CurrentFloor = 1
                        });
                });

            modelBuilder.Entity("WebApp.Models.ElevatorDestination", b =>
                {
                    b.Property<int>("ElevatorDestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ElevatorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("ElevatorDestinationId");

                    b.HasIndex("ElevatorId");

                    b.ToTable("ElevatorDestinations");
                });

            modelBuilder.Entity("WebApp.Models.ElevatorDestination", b =>
                {
                    b.HasOne("WebApp.Models.Elevator", "Elevator")
                        .WithMany("Destinations")
                        .HasForeignKey("ElevatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Elevator");
                });

            modelBuilder.Entity("WebApp.Models.Elevator", b =>
                {
                    b.Navigation("Destinations");
                });
#pragma warning restore 612, 618
        }
    }
}
